[package]
name = "wgpu-osm-view"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytemuck = { version = "1.16.3", features = ["derive"] }
cgmath = "0.18.0"
osmpbf = "0.3.4"
paste = "1.0.15"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = "0.29.0"
